version: '3.9'

services:
  db:
    image: mysql:8
    container_name: learninghub-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Beshu@2107
      MYSQL_DATABASE: learninghub
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: learninghub-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/learninghub
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Beshu@2107
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080
      SERVER_CONTEXT_PATH: /back1
    ports:
      - "8083:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: learninghub-frontend
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://54.89.231.208:8083/back1
    ports:
      - "9090:80"

volumes:
  db_data:
