version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: learninghub-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/learninghub
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Beshu@2107
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_ADDRESS: 0.0.0.0   
    ports:
      - "8083:8083"  # backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: learninghub-frontend
    restart: always
    ports:
      - "9090:8080"  # frontend Tomcat
    environment:
      VITE_API_URL: http://54.157.251.142:8083
